/*
 * This file is generated by jOOQ.
 */
package com.chengde.system.database.routines


import com.chengde.system.database.Public

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GenerateObjectId : AbstractRoutine<String>("generate_object_id", Public.PUBLIC, SQLDataType.VARCHAR) {
    companion object {

        /**
         * The parameter <code>public.generate_object_id.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<String?> = Internal.createParameter("RETURN_VALUE", SQLDataType.VARCHAR, false, false)
    }

    init {
        returnParameter = RETURN_VALUE
    }
}
