/*
 * This file is generated by jOOQ.
 */
package com.chengde.system.database.tables


import com.chengde.system.database.Public
import com.chengde.system.database.keys.APP_OF_USER_PKEY
import com.chengde.system.database.tables.records.AppOfUserRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AppOfUser(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AppOfUserRecord>?,
    aliased: Table<AppOfUserRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AppOfUserRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.app_of_user</code>
         */
        val APP_OF_USER: AppOfUser = AppOfUser()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AppOfUserRecord> = AppOfUserRecord::class.java

    /**
     * The column <code>public.app_of_user.id</code>.
     */
    val ID: TableField<AppOfUserRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.app_of_user.user_id</code>.
     */
    val USER_ID: TableField<AppOfUserRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.app_of_user.app_id</code>.
     */
    val APP_ID: TableField<AppOfUserRecord, Int?> = createField(DSL.name("app_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<AppOfUserRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AppOfUserRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.app_of_user</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.app_of_user</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.app_of_user</code> table reference
     */
    constructor(): this(DSL.name("app_of_user"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AppOfUserRecord>): this(Internal.createPathAlias(child, key), child, key, APP_OF_USER, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<AppOfUserRecord, Int?> = super.getIdentity() as Identity<AppOfUserRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<AppOfUserRecord> = APP_OF_USER_PKEY
    override fun `as`(alias: String): AppOfUser = AppOfUser(DSL.name(alias), this)
    override fun `as`(alias: Name): AppOfUser = AppOfUser(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AppOfUser = AppOfUser(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AppOfUser = AppOfUser(name, null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<Int?, Int?, Int?> = super.fieldsRow() as Row3<Int?, Int?, Int?>
}
