/*
 * This file is generated by jOOQ.
 */
package com.chengde.system.database.tables.references


import com.chengde.system.database.tables.App
import com.chengde.system.database.tables.AppOfUser
import com.chengde.system.database.tables.Note
import com.chengde.system.database.tables.User
import com.chengde.system.database.tables.Website



/**
 * The table <code>public.app</code>.
 */
val APP: App = App.APP

/**
 * The table <code>public.app_of_user</code>.
 */
val APP_OF_USER: AppOfUser = AppOfUser.APP_OF_USER

/**
 * The table <code>public.note</code>.
 */
val NOTE: Note = Note.NOTE

/**
 * The table <code>public.user</code>.
 */
val USER: User = User.USER

/**
 * The table <code>public.website</code>.
 */
val WEBSITE: Website = Website.WEBSITE
