/*
 * This file is generated by jOOQ.
 */
package com.chengde.system.database.tables.records


import com.chengde.system.database.tables.Website

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class WebsiteRecord() : UpdatableRecordImpl<WebsiteRecord>(Website.WEBSITE), Record2<String?, String?> {

    var name: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    var site: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row2<String?, String?> = super.fieldsRow() as Row2<String?, String?>
    override fun valuesRow(): Row2<String?, String?> = super.valuesRow() as Row2<String?, String?>
    override fun field1(): Field<String?> = Website.WEBSITE.NAME
    override fun field2(): Field<String?> = Website.WEBSITE.SITE
    override fun component1(): String? = name
    override fun component2(): String? = site
    override fun value1(): String? = name
    override fun value2(): String? = site

    override fun value1(value: String?): WebsiteRecord {
        this.name = value
        return this
    }

    override fun value2(value: String?): WebsiteRecord {
        this.site = value
        return this
    }

    override fun values(value1: String?, value2: String?): WebsiteRecord {
        this.value1(value1)
        this.value2(value2)
        return this
    }

    /**
     * Create a detached, initialised WebsiteRecord
     */
    constructor(name: String? = null, site: String? = null): this() {
        this.name = name
        this.site = site
    }
}
