/*
 * This file is generated by jOOQ.
 */
package com.chengde.system.database.routines.references


import com.chengde.system.database.routines.GenerateObjectId

import org.jooq.Configuration
import org.jooq.Field



/**
 * Call <code>public.generate_object_id</code>
 */
fun generateObjectId(
      configuration: Configuration
): String? {
    val f = GenerateObjectId()

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>public.generate_object_id</code> as a field.
 */
fun generateObjectId(): Field<String?> {
    val f = GenerateObjectId()

    return f.asField()
}
