/*
 * This file is generated by jOOQ.
 */
package com.chengde.system.database.keys


import com.chengde.system.database.tables.App
import com.chengde.system.database.tables.AppOfUser
import com.chengde.system.database.tables.Note
import com.chengde.system.database.tables.User
import com.chengde.system.database.tables.Website
import com.chengde.system.database.tables.records.AppOfUserRecord
import com.chengde.system.database.tables.records.AppRecord
import com.chengde.system.database.tables.records.NoteRecord
import com.chengde.system.database.tables.records.UserRecord
import com.chengde.system.database.tables.records.WebsiteRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val APP_NAME_UNIQUE: UniqueKey<AppRecord> = Internal.createUniqueKey(App.APP, DSL.name("app_name_unique"), arrayOf(App.APP.NAME), true)
val PK_APP_ID: UniqueKey<AppRecord> = Internal.createUniqueKey(App.APP, DSL.name("pk_app_id"), arrayOf(App.APP.ID), true)
val APP_OF_USER_PKEY: UniqueKey<AppOfUserRecord> = Internal.createUniqueKey(AppOfUser.APP_OF_USER, DSL.name("app_of_user_pkey"), arrayOf(AppOfUser.APP_OF_USER.ID), true)
val NOTE_PKEY: UniqueKey<NoteRecord> = Internal.createUniqueKey(Note.NOTE, DSL.name("note_pkey"), arrayOf(Note.NOTE.ID), true)
val PK_USER_ID: UniqueKey<UserRecord> = Internal.createUniqueKey(User.USER, DSL.name("pk_user_id"), arrayOf(User.USER.ID), true)
val USER_USERNAME_UNIQUE: UniqueKey<UserRecord> = Internal.createUniqueKey(User.USER, DSL.name("user_username_unique"), arrayOf(User.USER.USERNAME), true)
val WEBSITE_PKEY: UniqueKey<WebsiteRecord> = Internal.createUniqueKey(Website.WEBSITE, DSL.name("website_pkey"), arrayOf(Website.WEBSITE.NAME), true)
